<h1> Applying Naive Bayes Classifier <h1

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import pylab as pl
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import plot_confusion_matrix

<h2> Loading Data <h2>

In [10]:
arr2= np.load('data_array_non_formatted.npy', allow_pickle= True)
X= arr2[:,0:-1]
Y= arr2[:,-1]


### Split arrays or matrices into random train and test subsets - 20% for Test, 80% to train
X_train, X_test, y_train, y_test= train_test_split(X, Y, test_size=0.20)

print(X_train,y_train)
print(len(X_train),len(y_train),len(X_test),len(y_test))

[[30000000 7.978985000000001 98.0 ... 0 0 0]
 [21000000 7.814821 112.0 ... 0 0 0]
 [5000000 1.6719970000000002 178.0 ... 1 0 0]
 ...
 [13000000 4.673776999999999 96.0 ... 0 0 0]
 [20000000 11.11946 116.0 ... 1 0 0]
 [160000000 10.308026 102.0 ... 0 0 0]] ['Average' 'Average' 'Average' ... 'Bad' 'Average' 'Average']
5253 5253 1314 1314


<h2> Default Naive Bayes <h2>

In [11]:
#Using Naive Bayes

from sklearn.naive_bayes import GaussianNB

clf1 = GaussianNB()

clf1.fit(X_train, y_train); #train the classifier

print (clf1.score (X_test, y_test)) # print the testing score(accuracy)
print (clf1.score (X_train, y_train)) # print the trainig score(accuracy)

y_pred =clf1.predict(X_test)
print('F1 Score:',f1_score(y_test,y_pred,average='weighted'))

#lets print classification Report
print(classification_report(y_test, y_pred))

#Lets print confision matrix
print('Confusion Matrix values \n',confusion_matrix(y_test, y_pred))


0.7990867579908676
0.7905958499904816
F1 Score: 0.7098486428852885
              precision    recall  f1-score   support

     Average       0.80      1.00      0.89      1050
         Bad       0.00      0.00      0.00       171
        Good       0.00      0.00      0.00        93

    accuracy                           0.80      1314
   macro avg       0.27      0.33      0.30      1314
weighted avg       0.64      0.80      0.71      1314

Confusion Matrix values 
 [[1050    0    0]
 [ 171    0    0]
 [  93    0    0]]


C:\Users\Tasli\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
